on:
  push:
    branches:
      - distribute
      - macos
      - macos-arm64

name: Build MacOS arm64
jobs:
  build:
    name: Build MacOS arm64
    runs-on: macos-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_USER_SCP_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Compile Elm Generate
        run: ./scripts/build-generator-assets.sh
      - name: Run distribution script
        run: |
          mkdir -p ~/.local/bin
          curl https://downloads.haskell.org/~ghcup/aarch64-apple-darwin-ghcup -o ~/.local/bin/ghcup && chmod a+x ~/.local/bin/ghcup
          cd distribution
          ./build-macos-arm64.sh